### ISSUE TITLE
yarn build fails on unmet dep

### ISSUE THREAD

**Issue by twtaylor** [lightclients/kevlar#8] opened 2022-11-10 04:24 UTC
https://www.npmjs.com/package/json-rpc-engine doesn't appear to be pulled in properly. If you look at https://github.com/lightclients/kevlar/blob/90b1c7f2f56efa0669368ced93d12c1824f3dbd7/src/rpc-bundle/rpc-lightclient-middleware.ts#L1 the node module `json-rpc-engine` is not pulled in from anywhere.

So you'll get something like:

```
> yarn build
yarn run v1.22.19
$ tsc
src/rpc-bundle/rpc-lightclient-middleware.ts:1:39 - error TS2307: Cannot find module 'json-rpc-engine' or its corresponding type declarations.

1 import { createAsyncMiddleware } from 'json-rpc-engine';
                                        ~~~~~~~~~~~~~~~~~


Found 1 error in src/rpc-bundle/rpc-lightclient-middleware.ts:1

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you try to build.

**Comment by shresthagrawal** [comment] 2022-11-10 09:02
@twtaylor thanks for reporting the issue is fixed now

**Closed by shresthagrawal** 2022-11-10 09:02 UTC
